apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpoke
  namespace: kevinm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: quelpoke-kevinm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quelpoke-kevinm
    spec:
      containers:
        - name: quelpoke-kevinm
          image: europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn-2a588f0603e8/student-kevinm/quelpoke:1.0.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
