kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: quelpoke
  namespace: kevinm
spec:
  parentRefs:
    - kind: Gateway
      name: external-http-gateway
      namespace: infra
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /kevinm
      backendRefs:
        - name: quelpoke
          port: 8080
